### ISSUE TITLE
Wallet: Implementing Multi-wallet support (dev tracker)

### ISSUE THREAD

**Issue by HumbleDeer** [Raptor3um/Raptoreum#253]
Multi-wallet support is currently implemented on the daemon and/or RaptoreumCore CLI interface. 
This Issue is for keeping track of additional changes and/or discussion of Multi-Wallet support.

Outline:
- [x] Implement CLI support
- [ ] Implement GUI support
- [ ] Add documentation to repo about commands
- [ ] Add documentation to Raptoreum Docs (docs.raptoreum.com) 
    https://github.com/Raptor3um/raptoreum-docs/issues/56

Please link **past** ***and*** **presently pending** issues and/or pull requests relating to this feature!

@Raptor3um (Charlie) this would be a good candidate for moving into a Project with a filter view, as there will be multiple PR's and/or issues regarding implementation/bugs across more than one repository.

**Comment by HumbleDeer** [comment]
[Merge #13058: [wallet] createwallet RPC - create new wallet at runtime
](https://github.com/Raptor3um/raptoreum/commit/858a64f23d0802b0f68406912e9af914f457e80d)

> f7e153e95 [wallets] [docs] Add release notes for createwallet RPC. (John Newbery)
32167e830 [wallet] [tests] Add tests for `createwallet` RPC. (John Newbery)
942131774 [wallet] [rpc] Add `createwallet` RPC (John Newbery)

> Pull request description:
Adds a `createwallet` RPC to dynamically create a new wallet at runtime.
Includes tests and release notes.

Originally authored by DashCore dev team [here](https://github.com/dashevo/dash-evo-branches/commit/858a64f23d0802b0f68406912e9af914f457e80d) and later merged into RaptoreumCore.
